apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  namespace: udagram
  labels:
    app: reverseproxy
spec:
  selector:
    app: reverseproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
