apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  namespace: udagram
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: georgendirangu/udagram-frontend:v3
          resources:
            requests:
              memory: "750Mi"
              cpu: "500m"
            limits:
              memory: "750Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
