apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  namespace: udagram
  labels:
    app: udagram-frontend
spec:
  selector:
    app: udagram-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
