apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-api-user
  namespace: udagram
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 75
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-api-user
