apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  namespace: udagram
  labels:
    app: udagram-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
        - name: udagram-api-user
          image: georgendirangu/udagram-api-user:v2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_HOST
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_DB
                  optional: false
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_access_key_id
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_secret_access_key
                  optional: false
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_BUCKET
                  optional: false
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_REGION
                  optional: false
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_PROFILE
                  optional: false
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: JWT_SECRET
                  optional: false
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: URL
                  optional: false
